# Generated by Django 4.2.14 on 2024-08-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0003_rename_additionalinformation_userprofile_aboutme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='DOB',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobilenumber',
            field=models.IntegerField(),
        ),
    ]
