# Generated by Django 4.2.14 on 2024-08-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0004_alter_userprofile_dob_alter_userprofile_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='DOB',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobilenumber',
            field=models.CharField(max_length=300),
        ),
    ]
