# Generated by Django 4.2.14 on 2024-08-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0006_alter_userprofile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='projectimg',
            field=models.ImageField(upload_to='project_media'),
        ),
    ]
