# Generated by Django 4.2.14 on 2024-08-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0007_alter_userprofile_projectimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='projectimg',
            field=models.ImageField(blank=True, null=True, upload_to='project_media'),
        ),
    ]
